version: '3.7'

services:
    kitsune-bot:
        image: ghcr.io/topisenpai/kitsune-bot:latest
        container_name: kitsune-bot
        restart: unless-stopped
        env_file:
            - ./conf.env
        ports:
            - 80:80
